### ISSUE TITLE
pmatic-manager does not start

### ISSUE THREAD

**Issue by MFlasskamp** [LarsMichelsen/pmatic#2]
The pmatic-manager is not running. Starting it manually results in an ImportError:
```
# /usr/local/bin/python /usr/local/bin/pmatic-manager
Traceback (most recent call last):
  File "/usr/local/bin/pmatic-manager", line 66, in <module>
    import pmatic.manager
  File "/usr/local/etc/config/addons/pmatic/python/lib/python2.7/pmatic/manager.py", line 41, in <module>
    import inspect
ImportError: No module named inspect
```

**Comment by LarsMichelsen** [comment]
Thanks again! The module was missing in the pmatic CCU package. I have added all remaining missing ones now.

**Comment by MFlasskamp** [comment]
Unfortunately pmatic-manager is still not starting on the CCU2 with the current snapshot installed. It tries to connect remotely to a hardcoded IP:
```
# /usr/local/bin/python /usr/local/bin/pmatic-manager
Traceback (most recent call last):
  File "/usr/local/bin/pmatic-manager", line 114, in <module>
    manager = pmatic.manager.Manager((args.address, args.port))
  File "/usr/local/etc/config/addons/pmatic/python/lib/python2.7/pmatic/manager.py", line 1115, in __init__
    credentials=("Admin", "EPIC-SECRET-PW"))
  File "/usr/local/etc/config/addons/pmatic/python/lib/python2.7/pmatic/ccu.py", line 67, in __init__
    self.api = pmatic.api.init(**kwargs)
  File "/usr/local/etc/config/addons/pmatic/python/lib/python2.7/pmatic/api.py", line 91, in init
    return RemoteAPI(**kwargs)
  File "/usr/local/etc/config/addons/pmatic/python/lib/python2.7/pmatic/api.py", line 289, in __init__
    self.login()
  File "/usr/local/etc/config/addons/pmatic/python/lib/python2.7/pmatic/api.py", line 343, in login
    password=self._credentials[1])
  File "/usr/local/etc/config/addons/pmatic/python/lib/python2.7/pmatic/api.py", line 429, in call
    raise PMConnectionError("Unable to open \"%s\" [%s]: %s" % (url, type(e).__name__, msg))
pmatic.exceptions.PMConnectionError: Unable to open "http://192.168.1.26/api/homematic.cgi" [URLError]: [Errno 113] No route to host
```

**Comment by LarsMichelsen** [comment]
The issue you experience is related to the new bug #4 you reported. Will handle this issue there.
